services:
  alist:
    labels:
      "net.unraid.docker.icon": "https://pic.imgdb.cn/item/654c7a1cc458853aefb29f0f.png"
      # "net.unraid.docker.managed": "dockerman"
      "net.unraid.docker.shell": ""
      "net.unraid.docker.webui": "http://[IP]:[PORT:5244]/"
    image: xhofe/alist:latest
    container_name: alist
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
    volumes:
      - /mnt/user/appdata/alist:/opt/alist/data
    ports:
      - 5244:5244
    restart: unless-stopped
