services:
  ddns-go:
    labels:
      # "net.unraid.docker.icon": "https://raw.githubusercontent.com/0xJacky/nginx-ui/main/resources/logo.png"
      # "net.unraid.docker.managed": "dockerman"
      "net.unraid.docker.shell": ""
      "net.unraid.docker.webui": "http://[IP]:[PORT:9876]/"
    image: jeessy/ddns-go:latest
    container_name: ddns-go
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /mnt/user/appdata/ddns-go:/root
    ports:
      - 9876:9876
    restart: unless-stopped
