services:
  jellyfin:
    labels:
      "net.unraid.docker.icon": "https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/jellyfin-logo.png"
      # "net.unraid.docker.managed": "dockerman"
      "net.unraid.docker.shell": ""
      "net.unraid.docker.webui": "http://[IP]:[PORT:8096]/"
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
    volumes:
      - /mnt/user/appdata/jellyfin:/config
      - /mnt/user/media/tvshows:/data/tvshows
      - /mnt/user/media/movies:/data/movies
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 8096:8096
      # - 8920:8920 #optional
      # - 7359:7359/udp #optional
      # - 1900:1900/udp #optional
    restart: unless-stopped
