services:
  nginx-ui:
    labels:
      "net.unraid.docker.icon": "https://raw.githubusercontent.com/0xJacky/nginx-ui/main/resources/logo.png"
      # "net.unraid.docker.managed": "dockerman"
      "net.unraid.docker.shell": ""
      "net.unraid.docker.webui": "http://[IP]:[PORT:8088]/"
    image: uozi/nginx-ui:latest
    container_name: nginx-ui
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /mnt/user/appdata/nginx-ui/nginx:/etc/nginx
      - /mnt/user/appdata/nginx-ui/nginx-ui:/etc/nginx-ui
    ports:
      - 8088:80
      - 8443:443
    restart: unless-stopped
