services:
  prometheus:
    labels:
      "net.unraid.docker.icon": "https://raw.githubusercontent.com/selfhosters/unRAID-CA-templates/master/templates/img/prometheus.png"
      # "net.unraid.docker.managed": "dockerman"
      "net.unraid.docker.shell": ""
      "net.unraid.docker.webui": "http://[IP]:[PORT:9090]/"
    image: prom/prometheus
    container_name: prometheus
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /mnt/user/appdata/prometheus/config:/etc/prometheus
      - /mnt/user/appdata/prometheus/data:/prometheus
    ports:
      - 9090:9090
    restart: unless-stopped