services:
  qbittorrent:
    labels:
      "net.unraid.docker.icon": "https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/qbittorrent-icon.png"
      # "net.unraid.docker.managed": "dockerman"
      "net.unraid.docker.shell": ""
      "net.unraid.docker.webui": "http://[IP]:[PORT:8080]/"
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080
      - TORRENTING_PORT=10240
    volumes:
      - /mnt/user/appdata/qbittorrent:/config
      - /mnt/user/pt/downloads:/downloads
      - /mnt/user/pt/torrents:/torrents
    ports:
      - 8080:8080
      - 10240:10240
      - 10240:10240/udp
    restart: unless-stopped
